### ISSUE TITLE
Native linking error: file is universal (4 slices) but does not contain a(n) armv7s slice

### ISSUE THREAD

**Issue by bdrelling** [AppsFlyerSDK/XamariniOSBinding#1]
Received on Ad-Hoc or Release build:

Native linking error: file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/dev/Library/Caches/Xamarin/mtbs/builds/iOSP3OS/fb78f3b760efb55d25a603a36703d9fc/obj/iPhone/Ad-Hoc/mtouch-cache/libAppsFlyerLib.a file '/Users/dev/Library/Caches/Xamarin/mtbs/builds/iOSP3OS/fb78f3b760efb55d25a603a36703d9fc/obj/iPhone/Ad-Hoc/mtouch-cache/libAppsFlyerLib.a' for architecture armv7s

**Comment by AppsFlyerGit** [comment]
armv7s is not supported by Apple anymore.
