### ISSUE TITLE
Upgrade to latest native SDK 4.10.4

### ISSUE THREAD

**Issue by SoniaMartinReed** [AppsFlyerSDK/XamariniOSBinding#14]
Hi,

Now that there's a new SDK version available to support iOS13 and we got an email from you saying:
"You must update the AppsFlyer SDK on your iOS app to the newest version, in order to prevent obstruction to uninstall measurement."

It would be great if you could update this XamariniOSBinding to last native SDK 4.10.4

Thanks in advance.

**Comment by af-fess** [comment]
1.3.5
