### ISSUE TITLE
Notice of Deprecation: Older AppsFlyer SDK Versions

### ISSUE THREAD

**Issue by btripp** [AppsFlyerSDK/XamariniOSBinding#16]
Can you all create a XamariniOSBinding for the deprecation?

Platform | Sunsetting Versions
-- | --
Android | Below 4.8.5
iOS | Below 4.8.3
Windows | Below 2.3.0

**Comment by af-vs** [comment]
Closing as this doesn't seem to be relevant any longer. Please feel free to re-open if you think otherwise
