### ISSUE TITLE
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

### ISSUE THREAD

**Issue by bbhxwl** [AppsFlyerSDK/XamariniOSBinding#24]
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

**Comment by af-vs** [comment]
Hi!

If this is still relevant, please reopen and provide more details. Is this somehow related to AppsFlyer SDK? If not we can't just bind custom code as we are only maintaining AppsFlyer SDK.

Thank you!
