### ISSUE TITLE
6.2.4 Build Error

### ISSUE THREAD

**Issue by keab42** [AppsFlyerSDK/XamariniOSBinding#30]
We have updated our app from v6.0.3.0 to v6.2.4 but we are now seeing the following error when we try to build

`MTOUCH : error MT2101: Can't resolve the reference 'System.IntPtr ObjCRuntime.NativeObjectExtensions::GetNonNullHandle(ObjCRuntime.INativeObject,System.String)', referenced from the method 'System.Void AppsFlyerXamarinBinding.AppsFlyerLibDelegateWrapper::OnConversionDataSuccess(Foundation.NSDictionary)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.`

Are there any changes to the required versions of Xamarin or Visual Studio for Mac?

**Comment by af-vs** [comment]
Hi @keab42!

So far we use the latest available version of Xamarin to build the bindings, however, it seems that the better approach might be to use first major version. E.g. instead of instead of Xamarin.iOS 14.14.2.5 to use 14.0.0.0

To make sure this is the root cause, can you please specify which version of Xamarin.iOS do you currently have?

**Comment by af-vs** [comment]
@keab42 Please try the latest binding version 6.2.4.1, it should solve the issue
https://www.nuget.org/packages/AppsFlyerXamarinBinding/6.2.4.1

**Comment by keab42** [comment]
Thanks. We were able to resolve the issue on our end by updating our build agents to ensure they were running Xamarin iOS 14.14.2.5.

**Comment by nrudnyk** [comment]
> @keab42 Please try the latest binding version 6.2.4.1, it should solve the issue
> https://www.nuget.org/packages/AppsFlyerXamarinBinding/6.2.4.1

@af-vs what was the issue with your bindings and how did you managed to fix it?

**Comment by af-vs** [comment]
Hi @nrudnyk!

6.2.4.0 was build using the latest available Xamarin.iOS version, while for 6.2.4.1 we downgraded Xamarin.iOS to 14.0.0.0

**Comment by nrudnyk** [comment]
got it, thanks @af-vs
