### ISSUE TITLE
v6.2.3 Build Error

### ISSUE THREAD

**Issue by Syed-Esqimo** [AppsFlyerSDK/XamariniOSBinding#31]
Build failing in AppCenter with the following error:

```MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.ThrowHelper::ThrowArgumentNullException(System.String)', referenced from the method 'System.Void AppsFlyerXamarinBinding.AppsFlyerCrossPromotionHelper::LogAndOpenStore(System.String,System.String,Foundation.NSDictionary,System.Action`2<Foundation.NSUrlSession,Foundation.NSUrl>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ```

**Comment by Syed-Esqimo** [comment]
Hi, good morning @af-vs the build is failing in Microsoft AppCenter with the following config:
<img width="494" alt="Screenshot 2021-03-31 at 09 07 00" src="https://user-images.githubusercontent.com/51115792/113112248-e126be00-9200-11eb-9ff6-e2613a23120c.png">

 Builds fine locally.

**Comment by af-vs** [comment]
@Syed-Esqimo thanks for the info! Indeed looks like Xamarin.iOS version is the reason for the failure here. We will release shortly a new version of the binding (6.2.4.1) built with the Xamarin.iOS v14.0.0.0 to make sure compatibility with all the 14.x versions that may be used by the host applications. 

Thank you!

**Comment by Syed-Esqimo** [comment]
No problem! But can you please advise which Xamarin.iOS version is compatible with `6.2.4` so I can fix our build pipeline while we wait for the `6.2.4.1` release

**Comment by af-vs** [comment]
@Syed-Esqimo 6.2.4 should work with 14.14.2.5, same as you have installed locally and which is the latest version of Xamarin.iOS as of today. I am not sure about lower versions compatibility as we used the latest to build the binding.

But no worries, 6.2.4.1 is already available in NuGet :) 

https://www.nuget.org/packages/AppsFlyerXamarinBinding/6.2.4.1

Let us know if it solves the issue

**Comment by Syed-Esqimo** [comment]
Im happy to report the issue has been resolved with 6.2.4.1 release! That was some amazing and quck work Vitaly. Thank you sir!!!

Closing.
