### ISSUE TITLE
Upgrade to latest native SDK v6.4+

### ISSUE THREAD

**Issue by MatusevichMaxim** [AppsFlyerSDK/XamariniOSBinding#38]
Hi!
Could you please update the nuGet version to v6.4.0 (or latest stable at the moment)? 
Or it would be great to have a guide on how to do it manually (Binding AppsFlyer library).

**Comment by af-vs** [comment]
Hi @MatusevichMaxim

We will update the binding in the following days, which will be likely released early next week.

We prefer to keep doing it ourselves to provide the best support to the resulting product, but if you feel adventurous, you can get familiar with the Objective-C binding process [here](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/?context=xamarin/ios) and take a look at our Binding project [here](https://github.com/AppsFlyerSDK/XamariniOSBinding/tree/master/AppsFlyerXamarinBinding)

Thank you for your patience in the meantime!

**Comment by MatusevichMaxim** [comment]
Oh, thanks a lot for the fast reply! It's a great news. 
In the near future we'll try to repeat the binding process ourselves.

**Comment by af-vs** [comment]
New version is released [here](https://github.com/AppsFlyerSDK/XamariniOSBinding/releases/tag/v6.4.0.1)

Nuget package is also available in [Nuget Gallery](https://www.nuget.org/packages/AppsFlyerXamarinBinding/6.4.0.1)
