### ISSUE TITLE
v6.4.0.1 Build Error

### ISSUE THREAD

**Issue by rusohar** [AppsFlyerSDK/XamariniOSBinding#40]
After update to v6.4.0.1 build failing in AppCenter with the following error:

```MTOUCH` : error MT2101: Can't resolve the reference 'System.IntPtr CoreFoundation.CFString::CreateNative(System.String)', referenced from the method 'System.Void AppsFlyerXamarinBinding.AppsFlyerCrossPromotionHelper::LogAndOpenStore(System.String,System.String,Foundation.NSDictionary,System.Action`2<Foundation.NSUrlSession,Foundation.NSUrl>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.```

AppCenter use latest stable Xamarin.iOS 14.16. 
Is Xamarin.iOS 15 required?

**Comment by af-vs** [comment]
Hi!

Thanks for raising this up.

Yes, the latest version was built using Xamarin.iOS 15 from [here](https://github.com/xamarin/xamarin-macios/issues/12778).

However, let me check that, might be we can rebuild it with stable Xamarin.iOS 14 to provide the best compatibility. We will update here
