### ISSUE TITLE
Update to 6.5.4

### ISSUE THREAD

**Issue by keab42** [AppsFlyerSDK/XamariniOSBinding#43]
The last version published here was 6.4.0.3 could we get a new version built with 6.5.4?

**Comment by af-vs** [comment]
Hi @keab42!

We just released binding based on v6.5.4 [here](https://github.com/AppsFlyerSDK/XamariniOSBinding/releases/tag/v6.5.4.0) and it will also be available on NuGet within about 1 hour. 

Thank you!
