### ISSUE TITLE
IDFA is not collected

### ISSUE THREAD

**Issue by alekseyz** [AppsFlyerSDK/XamariniOSBinding#9]
Hi

During integration of appsflyer library we've faced an issue with IDFA collecting. Testing wizard showed that AdSupport.framework was not added.

Inside XamariniOSBinding there is 
[assembly: LinkWith ("libAppsFlyerLib.a", SmartLink = true, Frameworks="Security iAd", WeakFrameworks="AdSupport")]
and it did not work for us.
If we change it to 
[assembly: LinkWith ("libAppsFlyerLib.a", SmartLink = true, Frameworks="Security iAd AdSupport")] it works.
Hence, would you please assist us why AdSupport is added to WeakFrameworks and is that ok if IDFA is not collected?

**Comment by JSalazar88** [comment]
Anyone looking at this?

**Comment by servitola** [comment]
Any workaround?

**Comment by af-vs** [comment]
I believe this is no longer relevant. Latest versions of the binding should have the issue fixed. If you think otherwise, please re-open. Thank you!
